[workspace]
members = ["src/proxy", "src/canister_types", "src/test_helper"]
resolver = "2"

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.16"
ic-stable-structures = "0.6"
serde = "1.0"
serde_json = "1.0"
ic-ledger-types = "0.13"
pocket-ic = "5.0.0"
