[workspace]
members = ["src/proxy", "src/canister_types"]
resolver = "2"

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.15"
ic-stable-structures = "0.6"
serde = "1.0"
serde_json = "1.0"
ic-ledger-types = "0.12"

