[package]
name = "canister"
version = "0.1.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.14"
ic-stable-structures = "0.6"
serde = "1.0"
serde_json = "1.0"

ic-websocket-cdk = "0.3"

ic-cdk-timers = "0.6"

ic-ledger-types = "0.11"

email_address = "0.2"

unicode-segmentation = "1"

canister_types = { path = "../canister_types" }
catalyze-shared = { version = "0.1.0", path = "../../../catalyze-shared" }
